### ISSUE TITLE
FieldDescription::getValue does not allow to chain custom getter

### ISSUE THREAD

**Issue by rgrassian** [sonata-project/SonataDoctrineORMAdminBundle#1219]
## Feature Request

Hi,
I need to chain custom getters to add a field in a listMapper.

For instance I have 2 classes `Man` and `Dog` with the following methods :
```
Class Man {
    getDogs();

    // custom getter
    getFavoriteDog();
}
```
```
class Dog {
    getName();

    // custom getter
    getFormattedName();
}
```

`add('favoriteDog')` will work on ManAdmin and `add('formattedName')` will work on DogAdmin.
But `add('favoriteDog.formattedName')` will not display anything on ManAdmin.

From what I saw, the problem comes from FieldDescription::getValue which search only the first getter.

Does anyone have an idea to fix it without creating a new custom getter in my class `Man` ?

**Comment by VincentLanglet** [comment]
After some investigations, the issue seems to come from https://github.com/sonata-project/SonataDoctrineORMAdminBundle/blob/3.x/src/Model/ModelManager.php#L111-L135

Since it's a custom getter, `isset($metadata->associationMappings[$nameElement])` is `false` and `foreach` stops.
The `FieldDescription` has the following properties:
- `favoriteDog.formattedName` as name.
- `formattedName` as fieldName.
- No parent association mapping.

We should create a fake parent association mapping with an element `['fieldName' => 'favoriteDog']` instead.

As soon as we create a fake parent association mapping, we cannot know the `$class`, so the next iteration will also be some fake parent association mapping. And the return value should be 
```
return [null, implode('.', $properties), $parentAssociationMappings];
```
So our base code should be updated to support a nullable `ClassMetadata`.

We also have to update our code base to support this fake associationMapping. (for instance `$associationMapping['type']` need an `isset` check). 

WDYT @sonata-project/contributors ?

**Comment by franmomu** [comment]
> Does anyone have an idea to fix it without creating a new custom getter in my class `Man` ?

One way to solve it for now is adding a `virtual_field`:

```php
->add('whatever', null, [
    'template' => 'your_template.html.twig',
    'virtual_field' => true,
])
```
and then in twig you have access to `object` and you can call `object.favoriteDog.formattedName`.

Fake associations doesn't sound right, I haven't checked the code, but maybe we can add a `property_path` option and use `PropertyAccessor`.

**Comment by VincentLanglet** [comment]
> One way to solve it for now is adding a `virtual_field`:
> 
> ```
> ->add('whatever', null, [
>     'template' => 'your_template.html.twig',
>     'virtual_field' => true,
> ])
> ```
> 
> and then in twig you have access to `object` and you can call `object.favoriteDog.formattedName`.
 
You can currently use the template from Sonata: 
```
->add('favoriteDog', TEMPLATE_REGISTRY::TYPE_...)
```
if the getter already exist.

I feel sad with the fact to recommend to create a template instead for every custom field.
If you need to add this in list and show, you need 2 templates.
With the custom getter (which may be already implemented) it requires nothing.

So having a working
```
->add('favoriteDog.formattedName', TEMPLATE_REGISTRY::TYPE_TRANS)
```
wouldn't be bad for consistency.

> Fake associations doesn't sound right, I haven't checked the code, but maybe we can add a `property_path` option and use `PropertyAccessor`.

@franmomu I'm not familiar with PropertyAccesor. The code is here if you want to look at: https://github.com/sonata-project/SonataDoctrineORMAdminBundle/blob/3.x/src/Admin/FieldDescription.php#L93

It's mainly based on https://github.com/sonata-project/SonataAdminBundle/blob/3.x/src/Admin/BaseFieldDescription.php#L362-L418

It can maybe be improved by  using PropertyAccessor indeed. Do you have time to look at ?

Anyway, I think it would be nice to improve https://github.com/sonata-project/SonataDoctrineORMAdminBundle/blob/3.x/src/Model/ModelManager.php#L111-L135.
