### ISSUE TITLE
Review List field definition doc

### ISSUE THREAD

**Issue by eerison** [sonata-project/SonataDoctrineORMAdminBundle#1613]
Review the [List field definition](https://docs.sonata-project.org/projects/SonataDoctrineMongoDBAdminBundle/en/4.x/reference/list_field_definition) and see what can be moved to SonataAdminBundle.

Note: Look if make sense move part of this doc to https://docs.sonata-project.org/projects/SonataAdminBundle/en/4.x/reference/action_list/#customizing-the-fields-displayed-on-the-list-page or to other part of Sonata admin.

same thing to SonataDoctrineMongoDBAdminBundle: https://docs.sonata-project.org/projects/SonataDoctrineMongoDBAdminBundle/en/4.x/reference/list_field_definition

PR that was start this subject: https://github.com/sonata-project/SonataDoctrineORMAdminBundle/pull/1612

- [x] Move `types-available` to SonataAdmin doc
- [x] Move `list-actions` to Sonata Admin doc
- [x] Move `displaying-sub-entity-properties` to SonataAdmin doc
- [x] Move `custom-template` and `custom-route` to Sonata Admin doc
- [ ] #1622 (It depends of this PR: https://github.com/sonata-project/SonataAdminBundle/pull/7704)
- [ ] https://github.com/sonata-project/SonataDoctrineMongoDBAdminBundle/pull/724 (SonataDoctrineMongoDBAdminBundle)

**Comment by VincentLanglet** [comment]
To me:
- https://docs.sonata-project.org/projects/SonataDoctrineORMAdminBundle/en/4.x/reference/list_field_definition/#example is useless because we have https://docs.sonata-project.org/projects/SonataAdminBundle/en/4.x/reference/action_list/#customizing-the-fields-displayed-on-the-list-page
- https://docs.sonata-project.org/projects/SonataDoctrineORMAdminBundle/en/4.x/reference/list_field_definition/#types-available is only referencing SonataAdmin const, so it should be in sonataAdmin
- https://docs.sonata-project.org/projects/SonataDoctrineORMAdminBundle/en/4.x/reference/list_field_definition/#list-actions should be in SonataAdmin
- https://docs.sonata-project.org/projects/SonataDoctrineORMAdminBundle/en/4.x/reference/list_field_definition/#displaying-sub-entity-properties is in the todo of sonataAdmin (https://docs.sonata-project.org/projects/SonataAdminBundle/en/4.x/reference/action_list/#basic-configuration) so it's seems better to move it to sonataAdmin
- https://docs.sonata-project.org/projects/SonataDoctrineORMAdminBundle/en/4.x/reference/list_field_definition/#custom-template and https://docs.sonata-project.org/projects/SonataDoctrineORMAdminBundle/en/4.x/reference/list_field_definition/#custom-route are only related to sonataAdmin code so it should be inside the sonata admin doc.

So 100% of this page should be deleted/moved.

Same for https://docs.sonata-project.org/projects/SonataDoctrineMongoDBAdminBundle/en/4.x/reference/list_field_definition/
And (https://docs.sonata-project.org/projects/SonataDoctrineMongoDBAdminBundle/en/4.x/reference/list_field_definition/#custom-link is more detailled).

Do you want to do the PR @eerison ? :)

**Comment by eerison** [comment]
Yes @VincentLanglet I will do ;)
