### ISSUE TITLE
error with link rendering

### ISSUE THREAD

**Issue by markyboryslav** [sonata-project/SonataDoctrineORMAdminBundle#330]
after commit ec1949a98c1dddf79533db0b272f9573ad6e63ac
I have such problem:  

```
An exception has been thrown during the rendering of a template 
("Parameter "id" for  route 
"ru__RG__admin_topes_website_company_edit" 
must match "[^/]++" ("" given) to 
generate a corresponding URL.") in 
SonataDoctrineORMAdminBundle:CRUD:list_orm_many_to_one.html.twig at line 16.
```

It occurs when is the relationship between the User and the Company (many-to-one)

and i want to show company field in admin list

```php
 $listMapper
            ->addIdentifier('username') 
            ->add('company', null, array( )  )
```

**Comment by rschumacher** [comment]
The same happened to me these days, and I tried to identify the code that would generate something different then either a proper object or null. Because the twig template correctly checks against null.

The issue seems to happen in FieldDescription::getValue($object):
![screenshot 2015-03-22 um 14 16 18](https://cloud.githubusercontent.com/assets/179711/6769496/1bfce3cc-d09e-11e4-80ed-06f0db4cf2b2.png)
This is where the actual value for "items.parttype.parttypeGroup" (above example from redevelopers) is being fetched. However in case that either items or parttype are null, null should be returned by getValue(), but for some doesn't appear to happen. (A bit strange to be because when looking at the getFieldValue() code, it looks like it would behave properly i.e. return either null or the right value/object.)

So for me, the following small addition within the foreach loop resolved the problem:
![screenshot 2015-03-22 um 14 03 40](https://cloud.githubusercontent.com/assets/179711/6769445/5b2157b0-d09c-11e4-8a3f-7a2cd7cd8ca5.png)

Wondering whether this patch helps in you case as well.

**Comment by cacahouete78** [comment]
I have the same problem 
```
An exception has been thrown during the rendering of a template ("Parameter "id" for route "admin_proarti_dashboard_project_edit" must match "[^/]++" ("" given) to generate a corresponding URL.") in SonataDoctrineORMAdminBundle:CRUD:list_orm_many_to_one.html.twig at line 17.
```
i tried to put every thing in dev master , but the probleme is still there :s.

In my "configureListFields":
```php
             ->add('funds.project')
```
I just want to display in my list all projects where the user gave some funds.

I don t know why in BaseFieldDescription::getFieldValue he can't find the methode to get the value. I have checked that i didn't forget to create the getter, but he is there.

Someone have an idea to fix this issue ?

**Comment by SiliconMind** [comment]
@rande This problem is still present. Doctrine upgrade to 2.4 does not help, because it has nothing to do with doctrine.

The problem is caused by `SonataAdminExtension::getValueFromFieldDescription()` in `SonataAdmin` bundle. [This line](https://github.com/sonata-project/SonataAdminBundle/blob/master/Twig/Extension/SonataAdminExtension.php#L216) to be precise.

```PHP
public function getValueFromFieldDescription($object, FieldDescriptionInterface $fieldDescription, array $params = array())
    {
        if (isset($params['loop']) && $object instanceof \ArrayAccess) {
            throw new \RuntimeException('remove the loop requirement');
        }
        $value = null;
        try {
            $value = $fieldDescription->getValue($object);
        } catch (NoValueException $e) {
            if ($fieldDescription->getAssociationAdmin()) {
                $value = $fieldDescription->getAssociationAdmin()->getNewInstance();
                // We DON'T want new instance! We need null to render this correctly!
            }
        }
        return $value;
    }
```

As you can see a new instance of the class is returned if `FieldDescription::getValue()` throws `NoValueException` (and it WILL throw the exception if `$object` is `null`). New instance is not the same thing as `null`, but when this field is rendered with `list_orm_many_to_one.html.twig` [the template](https://github.com/sonata-project/SonataDoctrineORMAdminBundle/blob/master/Resources/views/CRUD/list_orm_many_to_one.html.twig) checks if `value` is `null`. New instance, even if has all null fields, is not the same thing as `null` value hence the exception when twig tries to render link by passing an instance of a class that has all fields equal to null.

```twig
{% block field %}
    {% if value %} {# at this point the check fails because new instance of a class is provided instead of null value #}
        {% if field_description.hasAssociationAdmin and field_description.associationadmin.hasRoute('edit') and field_description.associationadmin.isGranted('EDIT', value) %}
            <a href="{{ field_description.associationadmin.generateObjectUrl(field_description.options.route.name, value, field_description.options.route.parameters) }}">{{ value|render_relation_element(field_description) }}</a>
        {% else %}
            {{ value|render_relation_element(field_description) }}
        {% endif %}
    {% endif %}
{% endblock %}
```

It's hard for me to judge because I don't know if there are scenarios where new instance is really needed. All other places where `NoValueException` is caught, a null value is returned. This is the only place where new instance instead of null is returned.

So to fix this, either we won't create new instance or we check for value AND it's id if value is not null.

As for the quick fix, I'm going to override the twig template in my own project.

**Comment by SiliconMind** [comment]
A quick fix for twig template:

instead of this:

```twig
{% block field %}
    {% if value %}
        {# Blah blah blah #}
    {% endif %}
{% endblock %}
```

do this:
```twig
{% block field %}
    {% if value and field_description.associationadmin.getUrlsafeIdentifier(value) %}
        {# Blah blah blah #}
    {% endif %}
{% endblock %}
```

**Comment by iteratelance** [comment]
It appears that the method 

ModelManager::getIdentifierValues  is at the root of the issue here.

If you're using sonata admin and sore a list with a one_to_many the first item in the list will return an empty array for the first row.

```
    public function getIdentifierValues($entity)
    {
        // Fix code has an impact on performance, so disable it ...
        //$entityManager = $this->getEntityManager($entity);
        //if (!$entityManager->getUnitOfWork()->isInIdentityMap($entity)) {
        //    throw new \RuntimeException('Entities passed to the choice field must be managed');
        //}


        $class = $this->getMetadata(ClassUtils::getClass($entity));

        $identifiers = array();

        foreach ($class->getIdentifierValues($entity) as $value) {
            if (!is_object($value)) {
                $identifiers[] = $value;
                continue;
            }

            $class = $this->getMetadata(ClassUtils::getClass($value));

            foreach ($class->getIdentifierValues($value) as $value) {
                $identifiers[] = $value;
            }
        }

        return $identifiers;
    }
```

**Comment by webdevilopers** [comment]
Any news on this?

**Comment by gianarb** [comment]
Same problem..

**Comment by skobkin** [comment]
Same problem here.

```
doctrine/common                              v2.5.1
doctrine/dbal                                v2.5.2
doctrine/doctrine-bundle                     v1.5.2
doctrine/orm                                 v2.5.1
sonata-project/admin-bundle                  dev-master 684b6f5
sonata-project/core-bundle                   dev-master c4b5743
sonata-project/doctrine-orm-admin-bundle     dev-master 74e5033
```

Exception thrown on "create" page.

**Comment by boltunoreh** [comment]
In my case i've got almost same problem:
> An exception has been thrown during the rendering of a template ("Parameter "id" for route "admin_sonata_media_media_edit" must match "[^/]++" ("" given) to generate a corresponding URL.") in "SonataMediaBundle:Form:media_widgets.html.twig".

My entities:
- Survey
- SurveyQuestion (has sonata media image). It is many-to-one to Survey

So when I'm creating Survey, I add one SurveyQuestion, attach image with sonata-media, and then I want to add another one SurveyQuestion, but get this exception.

It is about the Image doesn't have an id, so method **generateObjectUrl('edit', value)** from __SonataMediaBundle:Form:media_widgets.html.twig line 6__ crushes.

So I solved this partially with rearranging default template, like it is said in [sonata docs](https://sonata-project.org/bundles/media/2-2/doc/reference/form.html).

I've just added this to my config.yml:
`    form:
        resources:
            - 'AppBundle:SurveyQuestionAdmin:media_widgets.html.twig'`

And my new template has just one more check to render the image's link and thumb - "and value.id" on lines 4 and 22:
`//media_widgets.html.twig
{% if value is not empty and value.providerReference and value.id %}
...
{% if value is not empty and value.providerReference and value.id %}`

Now there is no exception, but still have problem: non saved images attached to questions disappear after adding new SurveyQuestion.

So it's not a solution, but I'm on my way )

**Comment by mattchete** [comment]
@boltunoreh Have you found a solution to the disappearing elements after adding new ones ?

**Comment by boltunoreh** [comment]
@mattchete nope :(

**Comment by jordisala1991** [comment]
I think those issues are not related to the main issue which is 3 years old. 

Could you open new tickets for them? It will be easier for everyone having same problems
