### ISSUE TITLE
List view for big tables very slow due to DISTINCT query

### ISSUE THREAD

**Issue by AntonStoeckl** [sonata-project/SonataDoctrineORMAdminBundle#473]
There was an issue where this was mentioned but at the end not adressed: #297
We're using the SimplePager which indeed speeds things up as it does not do a count(...) query.

To visualize the difference, first one with DISTINCT, second one without:

```
drivenow_production=# explain analyze SELECT 
  DISTINCT e0_.id AS id_0, 
  e0_.timestamp AS timestamp_1 
FROM 
  EmittedEventRecord e0_ 
ORDER BY 
  e0_.timestamp DESC 
LIMIT 
  33 OFFSET 0;
                                                                       QUERY PLAN                                                                       
--------------------------------------------------------------------------------------------------------------------------------------------------------
 Limit  (cost=795326.66..795326.91 rows=33 width=45) (actual time=64059.389..64059.467 rows=33 loops=1)
   ->  Unique  (cost=795326.66..814667.44 rows=2578770 width=45) (actual time=64059.386..64059.432 rows=33 loops=1)
         ->  Sort  (cost=795326.66..801773.59 rows=2578770 width=45) (actual time=64059.384..64059.401 rows=33 loops=1)
               Sort Key: "timestamp", id
               Sort Method: external merge  Disk: 147920kB
               ->  Seq Scan on emittedeventrecord e0_  (cost=0.00..282727.70 rows=2578770 width=45) (actual time=0.040..48492.275 rows=2608727 loops=1)
 Total runtime: 64102.981 ms
```

```
drivenow_production=# explain analyze SELECT 
  e0_.id AS id_0, 
  e0_.timestamp AS timestamp_1 
FROM 
  EmittedEventRecord e0_ 
ORDER BY 
  e0_.timestamp DESC 
LIMIT 
  33 OFFSET 0;
                                                                                   QUERY PLAN                                                                                   
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 Limit  (cost=0.43..4.77 rows=33 width=45) (actual time=0.037..0.174 rows=33 loops=1)
   ->  Index Scan Backward using emittedeventrecordtimestamp on emittedeventrecord e0_  (cost=0.43..339144.15 rows=2578780 width=45) (actual time=0.034..0.115 rows=33 loops=1)
 Total runtime: 0.232 ms
```

Probably we can improve a bit by tuning Postgres, but generally I totally don't understand why doing DISTINCT on the primary key(s) field(s) is required?

It seems there is no sustainable way to change this behaviour as we'd have to overwrite a couple of services, so we'd have to change if the bundles are updated.

I guess a config option to disable the DISTINCT behaviour would do the job. This was suggested in the closed issue reference above but never done.

Best regards, Anton

**Comment by AntonStoeckl** [comment]
*ping*
If anybody can explain how to make this configurable we'll try to do a PR.
But it seems there is nothing to inject configurations into Datagrid/ProxyQuery.

**Comment by Soullivaneuh** [comment]
> But it seems there is nothing to inject configurations into Datagrid/ProxyQuery.

Well, you can try to make a PR with configuration injection. :+1:

**Comment by AntonStoeckl** [comment]
Just did a PR with a code change that should fix the issue in code.

**Comment by AntonStoeckl** [comment]
I don't see a way to inject any configuration into ProxyQuery without doing changes in SonataAdminBundle also. And  the distinct in the query is very specific for SonataDoctrineORMAdminBundle.
Any hints?

**Comment by AntonStoeckl** [comment]
The "best" solution I can see is something like this:

sonata_doctrine_orm_admin:
    entity_manager: postgresql
    disable_distinct_in_list_queries: 
        'some/entity/classname'
        'another/entity/classname'

But how to inject that config into ProxyQuery?

**Comment by Soullivaneuh** [comment]
Not sure if it will work with the actual logic.

cc @rande

**Comment by rande** [comment]
@Soullivaneuh I think there is a PR about integrating a simple pager which does not rely on count

**Comment by AntonStoeckl** [comment]
@rande Do you mean the simple pager that's already in master? We have that, it works without count but that does not solve the DISTINCT problem.

The more I think about it, the more I am sure that DISTINCT is not just not necessary but even wrong.
Two possible scenarios:

1) DB table identifier is unique (primary key): No distinct necessary, no matter if single or compound identifier, no matter if foreign key.

2) Identifier is NOT unique:
Let's assume there is a table where for each (distinct) identifier exactly 2 rows exist, let's say 100 rows in total. Distinct query now returns 32 distinct identifiers for the second query. But the second query returns 64 rows, as each identifier exists twice.

If nobody can draw a scenario where the distinct is needed or even useful, I insist that it should be completele removed. ;-)

**Comment by humanoyd** [comment]
I can't agree more, Why would one base the list on a non-unique identifier knowing he/she will get a list with hidden rows ?
Even if someone wants that for some reason, I can see that being the exception not the rule.

One can inject a custom DatagridBuilder through the DI that uses a custom ProxyQuery

A CompilePass/overrided service id/injection through admin service definition
Compiler pass example
```php
$adminServices = $container->findTaggedServiceIds('sonata.admin');

foreach ($adminServices as $id => $attributes) {
        $definition = $container->getDefinition($id);
        $definition->addMethodCall('setDatagridBuilder', array(new Reference('my.custom.datagrid_builder')));
}
```

**Comment by FractalizeR** [comment]
Did we reach any conclusion here? I don't see DISTICT neccessary there. It causes big performance issues for large tables on both MySQL 5.7 (Percona version at my project) and on Postgres too.

**Comment by OskarStark** [comment]
@FractalizeR thats all we got.
If you like you can propose an idea an we will discuss it with you.

**Comment by FractalizeR** [comment]
Thanks a lot, I will try to look into it and get back to you.

**Comment by FractalizeR** [comment]
I had a small look :) I am not experienced at all with Sonata internals, so please correct me if I am wrong.

So, the problem we have is inside `Sonata\DoctrineORMAdminBundle\Datagrid\ProxyQuery::getFixedQueryBuilder` method.

ProxyQuery class is a wrapper for Doctrine 2 query builder. Besides providing some `QueryBuilder` query methods, it is documented to

>add preselect id query on left join query, so a limit query will be only applied on the left statement and not on the full select statement. This simulates the original Doctrine 1 behavior.

So the first issue I see here is that I am not sure this speeds up anything. If you have a query with a join, as I know, a join will be executed regardless of the fields you listed in the `SELECT` clause. Looks like we just add a redundant query to extract ids first and then we issue the original query using ids as a condition. Can't we do without this first query, that selects ids and just do the original query once? Will it really slow something down?

Second issue I see here is that we have `$queryBuilderId->distinct();` call to ensure we do not have a repetable sets of primary key fields because original query could contain joins. Since `DISTINCT` is executed almost like a `GROUP BY`, adding this clause can cause serious performance degradation for queries with joins for instance. But inside `getFixedQueryBuilder` we work with already paginated resultset and we are selecting only like 50 to 150 items (to fit per page). Can't we just do this `DISTINCT` in PHP to simplify DB query plans? It would be easy to just filter out duplicates since the result set is very small.

And the third issue is that I think there is a small bug in the way we apply a filter when primary key is a composite one. We have a tricky line to apply a filter using id sets we've found:

```php
$queryBuilder->andWhere(sprintf('%s IN (:%s)', $selects[$idName], $idxParamName));
```

Imagine, we have the following data set rows:
 - Row №1: `(1, 2)`
 - Row №2: `(2, 1)`

When we will apply our fiter by ids it seems to have been expanded into the following condition: 
`WHERE id1 IN (1, 2) AND id2 IN (2, 1)`. But it's easy to provide a row outside the original resultset, that will satisfy this condition: `(1, 1)`, `(2, 2)`. So to correctly work with primary keys we have to do something like `(id1=1 AND id2=2) OR (id1=2 AND id2=1)`. If our primary key is not a composite one (99,9% of cases I believe) everything will be ok.

I'm sure I've made a shameful mistake somewhere and I will be glad to understand where.  If at least one of my findings is correct, I am ready to propose a PR with a fix.

**Comment by greg0ire** [comment]
A PR to allow disabling distinct would be good I think. If people disabling it report that it works fine, we might consider defaulting to no distinct. But first step IMO is disabling it. You can make PRs for the other issues too.

**Comment by jontorrado** [comment]
How is this going @FractalizeR @greg0ire ?

**Comment by greg0ire** [comment]
@jontorrado you can see for yourself: I got 2 upvotes, but no one proposed a PR.

**Comment by FractalizeR** [comment]
Sorry, guys, I am on vacations until about 9th. I will try to get to this ASAP.

**Comment by greg0ire** [comment]
Enjoy your hols! :palm_tree:

**Comment by eugenekurasov** [comment]
Hi, any news?

**Comment by zhil** [comment]
+1 , any news on this feature?
