### ISSUE TITLE
Admin can not render sonata_type_model field if entity use single table inheritance

### ISSUE THREAD

**Issue by biozshock** [sonata-project/SonataDoctrineORMAdminBundle#88]
Just discovered admin can not render a form where i'm editing Comment that attached to News class, which have a single table inheritance (STI) with Article. 
News class has admin class, while Article class obviously not.
After few hours of debugging i got that field which have STI have property `hasAssociationAdmin` set to `false`, so it rendered in another way than regular field with one-to-many.
If i create an admin class for Article field renders ok, but i do not want article class to appear in menu and services as it's useless.

**Comment by BenjaminBeck** [comment]
I do have a similar case:
The select field (manyToOne) for STI child-record is rendered correctly.
But if i want to render the STI parent-record it just displays the id as readonly textfield.

I can use ´´entity´´ instead of ´´sonata_type_model´´ then the select for the STI parent-record works as expected (shows all child-type records and parent-records) - but then i am missing the add-new button ):

Is this not supported or a bug?
